### ISSUE TITLE
Rayon support

### ISSUE THREAD

**Issue by sd2k** [Amanieu/hashbrown#16]
It'd be great to have Rayon compatibility for hashbrown's `HashMap` and `HashSet`. I think it's a case of implementing `IntoParallelIterator`, `FromParallelIterator` and `ParallelExtend`.

**Comment by cuviper** [comment]
Rayon's own implementations for `std::collections::{HashMap, HashSet}` are kind of cheating, by first dumping the items to a `Vec`, and then iterating that in parallel.  That's a little less bad for the indirect iterators (`par_iter` and `par_iter_mut`), but still not great.  We just don't have any access to split and iterate the raw tables directly.

A more useful reference might be [`rayon-hash`](https://github.com/rayon-rs/rayon-hash), where I cloned the `std` types and implemented parallel iterators with direct table access.  I imagine `hashbrown` could do something similar, but I haven't looked much at the internals here.

Collection is even trickier, as now you're talking about parallel mutation.  We currently just fold-reduce into a `LinkedList<Vec<_>>` and then serially insert items into the map/set, as this was the fastest approach in our benchmarks.  There's a neat idea in rayon-rs/rayon-hash#17 for better parallelism, but it requires some hash-indexing changes.

**Comment by hcpl** [comment]
I am tinkering this now, but no substantial progress so far (still learning internals of both `hashbrown` and `rayon-hash`).

So I have a question: is there a pressing demand to have Rayon support ASAP even if the performance is sub-par? The `Vec`-dumping implementations are trivial and seem to work for me, so that can be done quickly.

As for a "native" implementation, if no one takes this task, then I might roll out something in a few days. And hopefully that something will work.

**Comment by Amanieu** [comment]
Published in 0.1.8.
