### ISSUE TITLE
serde support

### ISSUE THREAD

**Issue by jkcclemens** [Amanieu/hashbrown#6]
A feature that enables these `Hash{Map,Set}`s to be used with serde (like `std::collections`) would be awesome.

**Comment by hcpl** [comment]
See https://github.com/Amanieu/hashbrown/issues/9 as an alternative solution to this issue, because `serde` already provides:
* [impl<K, V, H> Serialize for HashMap<K, V, H>](https://docs.rs/serde/1.0.80/serde/trait.Serialize.html#impl-Serialize-83)
* [impl<T, H> Serialize for HashSet<T, H> ](https://docs.rs/serde/1.0.80/serde/trait.Serialize.html#impl-Serialize-59)
* [impl<'de, K, V, S> Deserialize<'de> for HashMap<K, V, S>](https://docs.rs/serde/1.0.80/serde/trait.Deserialize.html#impl-Deserialize%3C%27de%3E-80)
* [impl<'de, T, S> Deserialize<'de> for HashSet<T, S>](https://docs.rs/serde/1.0.80/serde/trait.Deserialize.html#impl-Deserialize%3C%27de%3E-27)

So `hashbrown` only needs to expose its hasher for `serde` (and many other crates) to work!

**Comment by clbarnes** [comment]
#14 was merged before the 0.1.5 release, but I still can't `#[derive(Deserialize)]` on structs containing `hashbrown::HashMap`s in the same way that I can hashmaps from std, fxhash, or fnv. Is this expected?

```bash
error[E0277]: the trait bound `hashbrown::HashMap<T, T>: serde::Deserialize<'_>` is not satisfied
  --> src/main.rs:32:10
   |
32 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `hashbrown::HashMap<T, T>`
   |
   = note: required by `serde::de::SeqAccess::next_element`

error[E0277]: the trait bound `hashbrown::HashMap<T, T>: serde::Deserialize<'_>` is not satisfied
  --> src/main.rs:32:10
   |
32 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `hashbrown::HashMap<T, T>`
   |
   = note: required by `serde::de::MapAccess::next_value`
```

**Comment by hcpl** [comment]
@clbarnes sorry for a very late response, but if your issue hasn't been resolved yet, could you please share code that produces these errors?

> Is this expected?

The `Deserialize` impl for `hashbrown::HashMap` is a port from upstream implementation for std `HashMap` (https://docs.rs/serde/1.0.80/src/serde/de/impls.rs.html#1192-1236), so if your code worked for std, fxhash, or fnv then hashbrown should have worked out of the box too.

**Comment by clbarnes** [comment]
Sure thing!

https://github.com/clbarnes/hash_test/tree/master

Can't wait to use this library as soon as I can get the deserializing to work; thanks very much for your work.

**Comment by hcpl** [comment]
Oh, Serde support was made optional for hashbrown to reduce compile times for those who don't need it. So to make your code compile, just replace
```toml
hashbrown = "0.1.6"
```
with
```toml
hashbrown = { version = "0.1.6", features = ["serde"] }
```

The reason why Serde support worked for other cases is thanks to the combination of distinct factors:
* `std` provides two building blocks for creating hash maps: `RandomState` hasher implementation (which uses common `Hasher`/`BuildHasher` API) and `HashMap` implementation. Both are designed to be independently replaceable by third-party means.
* `fnv` and `fxhash` provide alternative _hasher_ implementations (which use faster hashing algorithms). For convenience, they provide type aliases `FnvHashMap<K, V>` and `FxHashMap<K, V>` that use the standard `HashMap` implementation so that you didn't have to write `HashMap<K, V, FnvBuildHasher>` and `HashMap<K, V, FxBuildHasher>` every single time.
* `hashbrown`, on the other hand, provides an alternative _`HashMap`_ implementation (which is faster than the standard one).
* `serde`'s definition of `Deserialize` for the standard `HashMap` implementation is generic over any hasher. That's why your `std_map`, `fx_map` and `fnv_map` cases all worked. But the definition of `Deserialize` for `hashbrown::HashMap` is in `hashbrown` and needs to be manually switched on.

Hope the explanation is able to clear your confusion!

**Comment by clbarnes** [comment]
Got it, didn't think about the feature flag. Thanks!
